server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
      name: meng-photo-album
  thymeleaf:
        mode: HTML
        encoding: utf-8
        cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.195.152:3306/meng_photo_album?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
   mapper-locations: classpath*:/mapper/**/*Mapper*.xml
mapper:
    #oracle true|mysql false
    before: false

logging:
    level:
      com.yansir.po.mengphotoalbum.mapper: DEBUG